### PR TITLE
Add font scale setting UI (#39) (WIP)

### PR DESCRIPTION
**Pull request by lydiascarf**
This is currently just the UI in the customization screen. Once the setting affects font sizing throughout the app, i'll mark this ready for review. Just posting now for fun :)

### CODE REVIEW

**Comment by elliottetzkorn** [comment]
Exciting!! Thanks for letting me know Lydia :)

**Comment by elliottetzkorn** [comment]
@lydiascarf I've updated this PR with a different approach - rather than keeping track of arrays with different text sizes, what if we just applied a scale multiplier in a few key locations? This seems to work quite well. Lmk what you think.

**Comment by lydiascarf** [comment]
i like it! i'll wrap this up tomorrow :)

**Comment by lydiascarf** [comment]
wait you did all of them! ig i need to move to quicker next time lol

i think this looks pretty good how you have it and i just added a couple commits to cleanup some unused code, to prevent the one bit of UI overflow i saw on my phone (on the edit profile page with large text), and to resolve the merge conflict. review/merge at your leisure <3

**Review by elliottetzkorn — APPROVED** [review]
Great, thanks for the comment

**Pull request merged**
